name: nwe_isee_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.8.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  url_launcher: ^6.1.7
  flutter_secure_storage: ^8.0.0
  image_picker: ^0.8.7+3
  syncfusion_flutter_pdfviewer: ^30.1.42
  fl_chart: ^0.64.0
  table_calendar: ^3.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_background.jpg
    - assets/errors/pv/sungrow/sungrow_shxxrt_errors.json 